name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github@example.com"
          git config --global user.name "GitHub Actions"
          npm install -g github-pages-deploy-action@v4
          npx gh-pages -d dist -b releases/v4 -u "${GITHUB_TOKEN}"
